"""Generate assets/facility/world-geo.js from public-domain Natural Earth 110m land.
Projects every coastline with the Equal Earth projection, normalizes to [0,1], decimates, and
emits compact paths + aligned city-node positions. Offline asset; no runtime network. Re-run only
when the source dataset changes.  Source: Natural Earth (public domain) ne_110m_land.geojson."""
import json, math, os

ROOT = r"C:\Users\ender\OneDrive\Desktop\Demo Portfolio"
SRC = os.path.join(ROOT, "assets", "data", "ne_110m_land.geojson")
OUT = os.path.join(ROOT, "assets", "facility", "world-geo.js")

A1, A2, A3, A4 = 1.340264, -0.081106, 0.000893, 0.003796
def eqearth(lon, lat):
    lam = math.radians(lon); phi = math.radians(lat)
    th = math.asin(math.sqrt(3) / 2 * math.sin(phi))
    x = 2 * math.sqrt(3) * lam * math.cos(th) / (3 * (9 * A4 * th**8 + 7 * A3 * th**6 + 3 * A2 * th**2 + A1))
    y = A4 * th**9 + A3 * th**7 + A2 * th**3 + A1 * th
    return x, y

XH = eqearth(180, 0)[0]     # half-width at equator, lon=180
YH = eqearth(0, 90)[1]      # half-height at pole, lon=0
def norm(lon, lat):
    x, y = eqearth(lon, lat)
    return (x + XH) / (2 * XH), (YH - y) / (2 * YH)   # y flipped for canvas top-down

def decimate(ring, eps=0.0035):
    out = [ring[0]]
    for p in ring[1:]:
        q = out[-1]
        if (p[0] - q[0]) ** 2 + (p[1] - q[1]) ** 2 >= eps * eps:
            out.append(p)
    if len(out) > 2 and out[0] != out[-1]:
        out.append(out[0])
    return out

data = json.load(open(SRC, encoding="utf-8"))
paths = []
for feat in data["features"]:
    geom = feat["geometry"]; polys = geom["coordinates"]
    if geom["type"] == "Polygon":
        polys = [polys]
    for poly in polys:
        outer = poly[0]                                   # outer ring only (ignore lakes at 110m)
        ring = [list(norm(c[0], c[1])) for c in outer]
        ring = decimate(ring)
        # drop specks: bbox area threshold in normalized space
        xs = [p[0] for p in ring]; ys = [p[1] for p in ring]
        if len(ring) < 4 or (max(xs) - min(xs)) * (max(ys) - min(ys)) < 0.00035:
            continue
        paths.append([[round(p[0], 4), round(p[1], 4)] for p in ring])

CITIES = {
    "YOW": (-75.67, 45.32, "Ottawa, Canada"), "SFO": (-122.4, 37.62, "San Francisco"),
    "LHR": (-0.45, 51.47, "London"), "FRA": (8.68, 50.11, "Frankfurt"),
    "DXB": (55.36, 25.25, "Dubai"), "SIN": (103.99, 1.36, "Singapore"),
    "NRT": (140.39, 35.77, "Tokyo"), "GRU": (-46.47, -23.43, "Sao Paulo"),
    "SYD": (151.18, -33.95, "Sydney"),
}
nodes = {k: {"p": [round(norm(v[0], v[1])[0], 4), round(norm(v[0], v[1])[1], 4)], "city": v[2]} for k, v in CITIES.items()}

js = ("/* world-geo.js — GENERATED by tools/gen_world_geo.py. Equal Earth projection of Natural\n"
      "   Earth 110m land (public domain). Normalized [0,1] coastline paths + aligned city nodes.\n"
      "   Offline; no runtime network. Do not hand-edit. */\n"
      "window.WORLD_GEO = " + json.dumps({"proj": "equal-earth", "paths": paths, "nodes": nodes},
                                         separators=(",", ":")) + ";\n")
open(OUT, "w", encoding="utf-8").write(js)
print("rings:", len(paths), " total points:", sum(len(p) for p in paths))
print("bytes:", os.path.getsize(OUT))
print("YOW:", nodes["YOW"]["p"], " SYD:", nodes["SYD"]["p"], " NRT:", nodes["NRT"]["p"])
